name: CI

on:
  push:
    branches: [ main, local-scaffold ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run smoke test
        run: |
          node backend/server.js &
          sleep 1
          curl -sS http://localhost:3000/api/health | jq .
